version: "2"

services:
  nats:
    image: nats:2.1.4
    ports:
      - "8222:8222"
      - "4222:4222"
      - "6222:6222"

  postgres:
    image: postgres:12.0
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: {}